import { IFeature } from "../pages";

export const polusFeatures: IFeature[] = [
  {
    id: 1,
    x: 42,
    y: 312,
    width: 11,
    height: 16,
    style: { cursor: "pointer", border: "2px solid lime" },
    label: "Manifolds",
    labelStyle: { color: "green" },
  },
  {
    id: 2,
    x: 149,
    y: 237,
    width: 23,
    height: 21,
    style: { cursor: "pointer", border: "2px solid lime" },
    label: "Engine Output",
    labelStyle: { color: "green" },
  },
  {
    id: 3,
    x: 62,
    y: 412,
    width: 22,
    height: 22,
    style: { cursor: "pointer", border: "2px solid lime" },
    label: "Start Reactor",
    labelStyle: { color: "green" },
  },
  {
    id: 4,
    x: 84,
    y: 271,
    width: 10,
    height: 16,
    style: { cursor: "pointer", border: "3px solid red" },
    label: "Reactor Meltdown",
    labelStyle: { color: "green" },
  },
  {
    id: 5,
    x: 82,
    y: 538,
    width: 13,
    height: 17,
    style: { cursor: "pointer", border: "3px solid red" },
    label: "Reactor Meltdown",
    labelStyle: { color: "green" },
  },
  {
    id: 6,
    type: "circ",
    x: 568,
    y: 410,
    width: 44,
    height: 22,
    style: { cursor: "pointer", border: "2px solid lime" },
    label: "Scan",
  },
];
